### ISSUE TITLE
[Add company]: CodeNext IT

### ISSUE THREAD

**Issue by imtiaz-cnits** [me-shaon/devhubbd-suggestions#1]
### Company name

CodeNext IT

### Company website link

https://www.codenextit.com/

### Company LinkedIn page

https://www.linkedin.com/company/codenextit/

### Company Facebook page

https://www.facebook.com/codenextit

### Company career page

https://www.codenextit.com/industrial-traning.html

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

No

### Office location

4th Floor, Hazi Akbar Ali Super Market, Abdul Hamid Road, Pabna, Bangladesh

### Established at

2021

### Total employees

1-10

### Primary tech stacks

MERN, Laravel, Figma

### Company description

CodeNext IT represents various hand-prints in tech industries by developing software, web applications, and websites, creating UI designs, and working with web templates in popular marketplaces like Themeforest and Template Monster. We also allow diploma-in-engineering students to take advantage of their industrial training. In addition to that, we also instruct new learners to spread the knowledge of these niches to our hometown and also the whole country.
Our ambitions are clear, we wanna create a historical mark on this industry by spreading knowledge, quality, and perfection.

**Comment by me-shaon** [comment]
Added.

**Comment by imtiaz-cnits** [comment]
Thanks brother
