### ISSUE TITLE
[Add company]: Coder Orbit

### ISSUE THREAD

**Issue by majadul1989** [me-shaon/devhubbd-suggestions#10]
### Company name

Coder Orbit

### Company website link

https://coderorbit.com

### Company LinkedIn page

https://www.linkedin.com/company/coderorbit/

### Company Facebook page

https://www.facebook.com/coderorbit/

### Company career page

https://coderorbit.com/career

### Work type

On-site, Hybrid, Fully remote

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

House #01, Lane #10
Road #11, Mirpur #11,  Dhaka-1216, Bangladesh

### Established at

2022

### Total employees

1-10

### Primary tech stacks

Laravel PHP, Vue (Nuxt), React (Next), Android, ISO (Flutter)

### Company description

we are trying to make a skill-able new orbit in the world, So why are you late to contribute with us?
We provide a professional API like below:
1. Ecommerce
2. Accountant Managment
3. POS (point of sale)
4. HRM (human resource managment)
5. CRM (customer relation managment)
6. Blog (CMS)

**Comment by me-shaon** [comment]
Added.
