### ISSUE TITLE
[Add company]: Esteem Soft Limited

### ISSUE THREAD

**Issue by winsharif** [me-shaon/devhubbd-suggestions#11]
### Company name

Esteem Soft Limited

### Company website link

http://esteemsoftbd.com/

### Company LinkedIn page

https://www.linkedin.com/company/esteemsoftbd

### Company Facebook page

https://www.facebook.com/esteemsoft

### Company career page

https://esteemsoftbd.com/career/

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

House # 77, Level # 2, Road # 2, Block # A, Bashundhara R/A, Dhaka-1229 ,Bangladesh.

### Established at

2011

### Total employees

11-50

### Primary tech stacks

LAMP

### Company description

Esteem Soft Limited is a private company founded in 2011. It has won 3 times national ICT awards for its innovative and cutting-edge solutions at Bashundhara R/A, Dhaka, Bangladesh. ARCH Hospital Management ERP software is our leading product in the market.

**Comment by me-shaon** [comment]
Added.
