### ISSUE TITLE
[Add company]: weDevs

### ISSUE THREAD

**Issue by mostafizurhimself** [me-shaon/devhubbd-suggestions#2]
### Company name

weDevs Ltd

### Company website link

https://wedevs.com

### Company LinkedIn page

https://www.linkedin.com/company/wedevs

### Company Facebook page

https://www.facebook.com/weDevs

### Company career page

https://wedevs.com/career

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

Level:03, House:1005,1007, Avenue:11, Road:09, Mirpur DOHS, Dhaka 1216

### Total employees

51-100

### Primary tech stacks

PHP, JavaScript, Node.js, Laravel, Wordpress, Vue.js, React.js, Typescript, etc.

### Company description

weDevs is the maker of Dokan Multivendor, WP User Frontend, WP Project Manager, WP ERP and some other exclusive WordPress products. We are innovators who are constantly making WordPress suitable for solving any kind of business problem. Our existence depends on making WordPress and SaaS products that help to scale your business.

**Comment by me-shaon** [comment]
Added.
