### ISSUE TITLE
[Add company]: 

### ISSUE THREAD

**Issue by freelancermahabubs** [me-shaon/devhubbd-suggestions#3]
### Company name

TechnoGenix Solutions

### Company website link

https://www.technogenixsolutions.com/

### Company LinkedIn page

https://www.linkedin.com/company/technogenix-solutions

### Company Facebook page

https://www.facebook.com/technogenixsolutions

### Work type

Fully remote

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

6/2, Kazi Nazrul Islam Road, Lalmatia, Dhaka 1207, BD

### Established at

2024

### Total employees

1-10

### Primary tech stacks

ASP.net, PHP, NodeJS, Laravel, Angular, React, VueJS, MySQL, Flutter, Swift, Kotlin, Redis, Selenium, SQA, FIGMA, Adobe, Autocad, Codeigniter, Rails, ExpressJS, Symfony, Svelte, ESLint, Redux, TypeScript, npn, webpack, VueX, Bootstrap, MariaDB, PostgreSQL, JAVA, WordPress, Dedicated extension teams, Project management, offshore development, QA & Test Automation, Augmented Reality, Virtual Reality, DevOps, Cloud & Cyber Security.

### Company description

TechnoGenix Solutions is a global software development and IT services-oriented company providing customized software development solutions backed by innovative & cutting-edge technology.

Providing local and Global IT Solutions, holding an impressive customer retention rate of more than 90%, thanks to our team of 10+ top-notch professionals. To help clients get the most value from data, we combine modern approaches with proven results, functional and analytical knowledge.
 
𝗢𝘂𝗿 𝗦𝗲𝗿𝘃𝗶𝗰𝗲𝘀 𝗮𝘁 𝗮 𝗚𝗹𝗮𝗻𝗰𝗲
- Customized Software Development 
- Talent Team Development
- Mobile App Development
- Web Application Development
- eCommerce Development
- QA and Test Automation
- Business Process Improvement
- Augmented Reality & Virtual Reality (AR/VR)
- Game Development
- DevOps

**Comment by me-shaon** [comment]
Added.
