### ISSUE TITLE
Glossy IT

### ISSUE THREAD

**Issue by NayeemHossenn** [me-shaon/devhubbd-suggestions#4]
### Company name

Glossy IT

### Company website link

https://www.glossyit.com/

### Company LinkedIn page

https://www.linkedin.com/company/glossyit/posts/?feedView=all

### Company Facebook page

https://www.facebook.com/GlossyIT/

### Company career page

https://www.glossyit.com/careers  

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

Mirpur Dohs, Dhaka

### Established at

2012

### Total employees

1-10

### Primary tech stacks

WordPress, Laravel

### Company description

Glossy IT is a trusted global provider of IT solutions and services, including web design and development, graphic design, branding, video and photo editing, and digital platform services. With 13+ years of experience and a client base of 1850+ businesses worldwide, we offer innovative, cost-effective solutions to meet our client’s requirements.

**Comment by me-shaon** [comment]
Added.
