### ISSUE TITLE
[Add company]: Softnio

### ISSUE THREAD

**Issue by 4msar** [me-shaon/devhubbd-suggestions#5]
### Company name

Softnio

### Company website link

https://softnio.com/

### Company LinkedIn page

https://www.linkedin.com/company/softnio

### Company Facebook page

https://www.facebook.com/softnio/

### Company career page

https://softnio.com/career/

### Work type

On-site, Hybrid

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

House #165, Lane No 3,
Mohakhali DOHS, Dhaka

### Established at

2012

### Total employees

11-50

### Primary tech stacks

Laravel, Wordpress, React, NextJS

### Company description

Softnio has been providing quality services to clients from different countries like Canada, USA, Australia, United Kingdom etc. Over than 8 years of experience in designing and developing websites beside we are creating product for global market place.

**Comment by adityakalburgi** [comment]
hello can you please explain what the issue is?

**Comment by me-shaon** [comment]
Added.
