### ISSUE TITLE
[Add company]: 

### ISSUE THREAD

**Issue by dipu-sultan** [me-shaon/devhubbd-suggestions#6]
### Company name

Techetron Ventures Ltd

### Company website link

https://www.techetronventures.com/

### Company LinkedIn page

https://www.linkedin.com/company/techetron-ventures-ltd/

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

Gulshan 2, Dhaka, Bangladesh

### Established at

2021

### Total employees

11-50

### Primary tech stacks

Go, Javascript, NextJS, React, Kotlin, Swift

### Company description

Incepted in 2021 by experts in the Tech and Marketing world, Techetron Ventures Ltd. specializes in providing next-generation marketing and branding solutions as well as pioneering Technological Products, with a vision to redefine the industry standards.

**Comment by me-shaon** [comment]
Added.
