### ISSUE TITLE
[Add company]: FIGLAB

### ISSUE THREAD

**Issue by phpfour** [me-shaon/devhubbd-suggestions#7]
### Company name

FIGLAB

### Company website link

https://figlab.io

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

Suite 5C, Haque Chamber, 89/2 West Panthapath, Dhaka 1215

### Established at

2022

### Total employees

11-50

### Primary tech stacks

PHP, Laravel, MySQL, React

### Company description

FIGLAB builds exceptional web applications. Our product-focused teams help brands, organizations, and startups ideate and launch digital products with a fully aligned process that puts users first.

**Comment by me-shaon** [comment]
Added.
