### ISSUE TITLE
[Add company]: 

### ISSUE THREAD

**Issue by ridislam** [me-shaon/devhubbd-suggestions#8]
### Company name

iNiLabs

### Company website link

https://inilabs.net

### Company LinkedIn page

https://www.linkedin.com/company/14437981

### Company Facebook page

https://www.facebook.com/inilabs

### Work type

On-site

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

Mirpur 2, Dhaka, Bangladesh

### Established at

2016

### Total employees

11-50

### Primary tech stacks

Laravel, Flutter

### Company description

iNiLabs is a software company that enables businesses to connect with their customers in more meaningful ways. We provide a suite of cloud-based software tools that allow businesses to create and manage their organizations. We also offer a variety of services to help businesses get the most out of our products, including implementation, training, and support. Our goal is to help businesses connect with their customers in more meaningful ways, so they can continue to grow and succeed.

**Comment by me-shaon** [comment]
Added.
