### ISSUE TITLE
[Add company]: UnivaHost

### ISSUE THREAD

**Issue by ShiponKarmakar** [me-shaon/devhubbd-suggestions#9]
### Company name

UnivaHost

### Company website link

https://univahost.com

### Company Facebook page

https://www.facebook.com/UnivaHost.Page/

### Work type

Hybrid, Fully remote

### Hires freshers?

Yes

### Hires interns?

Yes

### Office location

15, 1012/1 Ahmed Plaza, Level 2, Court Road, Brahmanbaria 3400, Bangladesh.

### Established at

2016

### Total employees

1-10

### Primary tech stacks

PHP, Server Management

### Company description

UnivaHost is leading World-Wide Domain Hosting Platform. UnivaHost is a dedicated web hosting company that offers World-wide Domain Hosting, Reseller Hosting, Shared Hosting, VPS server, Dedicated Server, Cheap rate Domain name at affordable price. So, let's come, join us and spark your business with us.

**Comment by ShiponKarmakar** [comment]
https://www.linkedin.com/company/univa-host

**Comment by me-shaon** [comment]
Added.
